# Generated by Django 3.2.12 on 2022-04-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='balance',
        ),
    ]
