# Generated by Django 3.2.12 on 2022-04-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Balance',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='balance',
        ),
    ]
